import { useEffect, useMemo, useState } from "react";
import { Inbox, MessageCircle, Search, Star } from "lucide-react";
import { listInboxThreads } from "./communicationRepository";
import type { InboxThread } from "./types";

const labels={message:"Message",comment:"Commentaire",mention:"Mention",review:"Avis"};
export function CommunicationInbox(){
 const [threads,setThreads]=useState<InboxThread[]>([]);const [query,setQuery]=useState("");const [filter,setFilter]=useState("all");const [loading,setLoading]=useState(true);
 useEffect(()=>{void listInboxThreads().then(setThreads).catch(()=>setThreads([])).finally(()=>setLoading(false));},[]);
 const visible=useMemo(()=>threads.filter(t=>(filter==="all"||t.kind===filter)&&`${t.contact_name} ${t.subject}`.toLowerCase().includes(query.toLowerCase())),[filter,query,threads]);
 return <section className="overflow-hidden rounded-2xl border border-subtle bg-surface shadow-sm"><header className="flex flex-col gap-3 border-b border-subtle p-4 md:flex-row"><label className="flex flex-1 items-center gap-2 rounded-xl border border-subtle px-3"><Search className="h-4 w-4 text-muted"/><input value={query} onChange={e=>setQuery(e.target.value)} className="w-full bg-transparent py-2.5 text-sm outline-none" placeholder="Rechercher un message, commentaire ou avis…"/></label><select value={filter} onChange={e=>setFilter(e.target.value)} className="rounded-xl border border-subtle bg-surface px-3 py-2 text-sm text-ink"><option value="all">Toutes les conversations</option><option value="message">Messages</option><option value="comment">Commentaires</option><option value="mention">Mentions</option><option value="review">Avis</option></select></header>{loading?<p className="p-8 text-center text-muted">Synchronisation…</p>:visible.length?<div className="divide-y divide-subtle">{visible.map(thread=><article key={thread.id} className="grid gap-3 p-4 hover:bg-interactive md:grid-cols-[180px_1fr_auto]"><div><p className="font-medium text-ink">{thread.contact_name||"Contact"}</p><p className="text-xs text-muted">{thread.account_name}</p></div><div><span className="rounded-full bg-primary-soft px-2 py-1 text-xs text-primary-on">{labels[thread.kind]}</span><p className="mt-2 text-sm text-ink">{thread.subject||"Nouvelle interaction"}</p></div><time className="text-xs text-muted">{new Date(thread.last_message_at).toLocaleString("fr-FR")}</time></article>)}</div>:<div className="flex min-h-72 flex-col items-center justify-center p-8 text-center"><Inbox className="h-10 w-10 text-primary"/><h2 className="mt-3 font-semibold text-ink">Boîte de réception unifiée</h2><p className="mt-1 max-w-lg text-sm text-muted">Les messages, commentaires, mentions et avis apparaîtront ici dès qu’un compte sera connecté et synchronisé.</p><div className="mt-5 flex gap-4 text-xs text-muted"><span className="flex items-center gap-1"><MessageCircle className="h-4 w-4"/>Réponses assignables</span><span className="flex items-center gap-1"><Star className="h-4 w-4"/>Avis Google</span></div></div>}</section>;
}
